spring:
  application:
    name: LogisticsFuture

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION}

server:
  port: ${PORT:2025}

spring.config.import: optional:classpath:/application.yml

logging:
  level:
    org:
      springframework:
        web: INFO