spring:
  application:
    name: LogisticsFuture

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${SMTP_HOST}  # Render SMTP settings
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION}

server:
  port: ${PORT}

spring.config.import: optional:classpath:/application.yml

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL}
